FROM node:18-alpine

RUN apk add --no-cache git && \
    git config --global --add safe.directory /app

WORKDIR /app

COPY src/frontend/package*.json ./

RUN npm ci

ENV CHOKIDAR_USEPOLLING=true

ENV PORT=3000
EXPOSE 3000

CMD ["npm", "start"]
